openapi: 3.1.0

components:
  schemas:
    ValidationError:
      type: object
      properties:
        message:
          type: string
        data:
          type: array
          items:
            type: string
          example: ['O campo de nome [name] não deve estar vazio']
