openapi: 3.1.0
tags:
  - name: Categorias
    description: Operações relacionadas ao recurso de Categorias

paths:
  /categorias:
    get:
      summary: Lista todas as categorias.
      tags:
        - Categorias
      responses:
        200:
          description: Sucesso. Retorna a lista de categorias.
          content:
            application/json:
              example:
                message: Categorias encontradas com sucesso
                data:
                  - id: 1
                    nome: Automotivo
                  - id: 2
                    nome: Móveis
                  - id: 3
                    nome: Informática
    post:
      summary: Cria uma nova categoria.
      tags:
        - Categorias
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                juros:
                  type: number
      responses:
        201:
          description: Sucesso. Retorna os detalhes da categoria criada.
          content:
            application/json:
              example:
                message: Categoria criada com sucesso
                data:
                  id: 4
                  nome: string

        400:
          description: Erro de validação dos dados.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'

  /categorias/{id}:
    get:
      summary: Obtém uma categoria específica pelo ID.
      tags:
        - Categorias
      parameters:
        - in: path
          name: id
          required: true
          description: ID da categoria a ser obtida.
          schema:
            type: integer
      responses:
        '200':
          description: Sucesso. Retorna os detalhes da categoria encontrada.
          content:
            application/json:
              example:
                message: Categoria encontrada com sucesso
                data:
                  id: 3
                  nome: Informática
                  juros: 5
        '404':
          description: Categoria não encontrada. Retorna uma mensagem de erro.
          content:
            application/json:
              example:
                message: A categoria informada não foi encontrada
    patch:
      summary: Atualiza uma categoria específica pelo ID.
      tags:
        - Categorias
      parameters:
        - in: path
          name: id
          required: true
          description: ID da categoria a ser atualizada.
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                juros:
                  type: number
      responses:
        '400':
          description: Erro de validação. Retorna uma mensagem de erro.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '200':
          description: Sucesso. Retorna os detalhes da categoria atualizada.
          content:
            application/json:
              example:
                message: Categoria atualizada com sucesso
                data:
                  id: 3
                  nome: Informática
                  juros: 2
        '404':
          description: Categoria não encontrada. Retorna uma mensagem de erro.
          content:
            application/json:
              example:
                message: A categoria informada não foi encontrada
    delete:
      summary: Deleta uma categoria específica pelo ID.
      tags:
        - Categorias
      parameters:
        - in: path
          name: id
          required: true
          description: ID da categoria a ser deletada.
          schema:
            type: integer
      responses:
        '204':
          description: Categoria deletada com sucesso. Sem corpo de resposta.

        '404':
          description: Categoria não encontrada. Retorna uma mensagem de erro.
          content:
            application/json:
              example:
                message: A categoria informada não foi encontrada
